// CPPATL.idl : IDL source for CPPATL
//

// This file will be processed by the MIDL tool to
// produce the type library (CPPATL.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6E9EC4DA-8970-4C42-B8D7-17032692A34E),
	version(1.0),
]
library CPPATLLib
{
	importlib("stdole2.tlb");
};

