FROM ubuntu

ENV INSTALL_PATH /myapp/sub/sub
RUN mkdir /myapp
RUN mkdir /myapp/sub
RUN mkdir /myapp/sub/sub
WORKDIR $INSTALL_PATH
COPY ./scimark2 $INSTALL_PATH
COPY ./docker-entrypoint.sh $INSTALL_PATH
ENTRYPOINT ["/myapp/sub/sub/docker-entrypoint.sh"]
